### ISSUE TITLE
window recording is clipped

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra-selenoid-connector#14]
I'm testing with `tt.display.resolution=1920x1200` resolution but
recording is done with 1920x1080 in such a way, that 120 pixels from the bottom are clipped. 

I assume that 1920x1200 window should be scaled to 1920x1080, or recording resolution should match `tt.display.resolution`.

**Comment by gogro** [comment]
workaround : set 
tt.display.resolution=1920x1080
in test.properties
we are working on a better default behaviour. thanks for bringing this to our attention.
